// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WishlistApp.API.Data;

#nullable disable

namespace WishlistApp.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WishlistApp.API.Models.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                b.Property<string>("AvatarUrl").HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("WishlistApp.API.Models.WishlistItem", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<decimal?>("Price").HasColumnType("decimal(18,2)");
                b.Property<string>("PhotoUrl").HasColumnType("text");
                b.Property<string>("SourceUrl").HasColumnType("text");
                b.Property<string>("Description").HasColumnType("text");
                b.Property<int>("Priority").HasColumnType("integer");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.Property<bool>("IsDeleted").HasColumnType("boolean");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("WishlistItems");
            });
#pragma warning restore 612, 618
        }
    }
}
